require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/transaction_histories", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TransactionHistory. As you add validations to TransactionHistory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TransactionHistory.create! valid_attributes
      get transaction_histories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      transaction_history = TransactionHistory.create! valid_attributes
      get transaction_history_url(transaction_history)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_transaction_history_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      transaction_history = TransactionHistory.create! valid_attributes
      get edit_transaction_history_url(transaction_history)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TransactionHistory" do
        expect {
          post transaction_histories_url, params: { transaction_history: valid_attributes }
        }.to change(TransactionHistory, :count).by(1)
      end

      it "redirects to the created transaction_history" do
        post transaction_histories_url, params: { transaction_history: valid_attributes }
        expect(response).to redirect_to(transaction_history_url(TransactionHistory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TransactionHistory" do
        expect {
          post transaction_histories_url, params: { transaction_history: invalid_attributes }
        }.to change(TransactionHistory, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post transaction_histories_url, params: { transaction_history: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested transaction_history" do
        transaction_history = TransactionHistory.create! valid_attributes
        patch transaction_history_url(transaction_history), params: { transaction_history: new_attributes }
        transaction_history.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the transaction_history" do
        transaction_history = TransactionHistory.create! valid_attributes
        patch transaction_history_url(transaction_history), params: { transaction_history: new_attributes }
        transaction_history.reload
        expect(response).to redirect_to(transaction_history_url(transaction_history))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        transaction_history = TransactionHistory.create! valid_attributes
        patch transaction_history_url(transaction_history), params: { transaction_history: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested transaction_history" do
      transaction_history = TransactionHistory.create! valid_attributes
      expect {
        delete transaction_history_url(transaction_history)
      }.to change(TransactionHistory, :count).by(-1)
    end

    it "redirects to the transaction_histories list" do
      transaction_history = TransactionHistory.create! valid_attributes
      delete transaction_history_url(transaction_history)
      expect(response).to redirect_to(transaction_histories_url)
    end
  end
end
